# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.4"

package:
  name: ruamel-yaml-line-info
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/ruamel-yaml-line-info/ruamel_yaml_line_info-${{ version }}.tar.gz
  sha256: 8cb81a11671a341693af713c70d0b58e0cee2b39ece4ffb413a333c91edd21f8

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.6
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - ruamel.yaml >=0.18.10,<0.19.0

tests:
  - python:
      imports: ruamel_yaml_line_info
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pytest-cov
        - mypy
    files:
      source:
        - tests/
    script:
      - coverage run --source=ruamel_yaml_line_info --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=92
      - mypy -p ruamel_yaml_line_info

about:
  summary: Line information for ruamel.yaml.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/nh13/ruamel_yaml_line_info

extra:
  recipe-maintainers:
    - bollwyvl
